# Generated by Django 4.2.3 on 2025-10-01 08:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import judging.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends', '0005_friendsmembershiplog'),
        ('application', '0036_broadcast_outbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgingRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default rubric', max_length=120)),
                ('version', models.PositiveIntegerField(help_text='Increment every time you update the rubric definition.')),
                ('definition', models.JSONField(default=judging.models.default_rubric_definition)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_rubrics', to='application.edition')),
            ],
            options={
                'ordering': ['-edition_id', '-version'],
                'unique_together': {('edition', 'version')},
            },
        ),
        migrations.CreateModel(
            name='JudgingReleaseWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('csv_snapshot_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_release_windows', to='application.edition')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judging_release_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='JudgingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('table_location', models.CharField(blank=True, max_length=80)),
                ('track', models.CharField(blank=True, max_length=80)),
                ('qr_slug', models.CharField(editable=False, max_length=12, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Public projects appear in the released leaderboard.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_projects', to='application.edition')),
                ('friends_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judging_projects', to='friends.friendscode')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JudgingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('released', 'Released')], default='draft', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_evaluations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='judging.judgingproject')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='judging.judgingrubric')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('released', 'Released')], max_length=16)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judging_events', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='judging.judgingevaluation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='judgingreleasewindow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('edition',), name='unique_active_window_per_edition'),
        ),
        migrations.AlterUniqueTogether(
            name='judgingproject',
            unique_together={('edition', 'friends_code')},
        ),
        migrations.AlterUniqueTogether(
            name='judgingevaluation',
            unique_together={('project', 'judge', 'rubric')},
        ),
    ]
