# Generated by Django 4.2.3 on 2025-09-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_add_devpost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendscode',
            name='track_assigned',
            field=models.CharField(blank=True, choices=[('interactive_media', 'Interactive Media'), ('social_good', 'Social Good'), ('all_health', 'All Health'), ('fintech', 'FinTech'), ('smart_cities', 'Smart Cities'), ('open_innovation', 'Open Innovation')], max_length=40),
        ),
        migrations.AddField(
            model_name='friendscode',
            name='track_assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friendscode',
            name='track_pref_1',
            field=models.CharField(blank=True, choices=[('interactive_media', 'Interactive Media'), ('social_good', 'Social Good'), ('all_health', 'All Health'), ('fintech', 'FinTech'), ('smart_cities', 'Smart Cities'), ('open_innovation', 'Open Innovation')], max_length=40),
        ),
        migrations.AddField(
            model_name='friendscode',
            name='track_pref_2',
            field=models.CharField(blank=True, choices=[('interactive_media', 'Interactive Media'), ('social_good', 'Social Good'), ('all_health', 'All Health'), ('fintech', 'FinTech'), ('smart_cities', 'Smart Cities'), ('open_innovation', 'Open Innovation')], max_length=40),
        ),
        migrations.AddField(
            model_name='friendscode',
            name='track_pref_3',
            field=models.CharField(blank=True, choices=[('interactive_media', 'Interactive Media'), ('social_good', 'Social Good'), ('all_health', 'All Health'), ('fintech', 'FinTech'), ('smart_cities', 'Smart Cities'), ('open_innovation', 'Open Innovation')], max_length=40),
        ),
    ]
