# Generated by Django 4.2.3 on 2025-09-05 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0004_friendscode_track_assigned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsMembershipLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('move', 'Move')], max_length=8)),
                ('from_code', models.CharField(blank=True, max_length=20)),
                ('to_code', models.CharField(blank=True, max_length=20)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_actions', to=settings.AUTH_USER_MODEL)),
                ('affected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_membership_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
