# Generated by Django 4.2.3 on 2025-10-08 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_edition_judging_scores_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0005_friendsmembershiplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendscode',
            name='seeking_merge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendscode',
            name='seeking_merge_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FriendsMergePoolEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_code', models.CharField(max_length=13)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('removed', 'Removed')], default='pending', max_length=16)),
                ('trigger', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('deadline', 'Deadline')], default='auto', max_length=16)),
                ('matched_team_code', models.CharField(blank=True, max_length=13)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_pool_entries', to='application.edition')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('edition', 'team_code')},
            },
        ),
        migrations.CreateModel(
            name='FriendsMergeEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('opt_in', 'Opt-in'), ('matched', 'Matched'), ('removed', 'Removed from pool'), ('notified', 'Notification sent')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_events', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='friends.friendsmergepoolentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
