# Generated by Django 4.2.3 on 2025-10-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0007_alter_friendscode_track_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendscode',
            name='track_assigned',
            field=models.CharField(blank=True, choices=[('fintech', 'Fintech by Capital One'), ('interactive_media', 'Smart Intelligence by GateGroup'), ('social_good', 'Smart Execution by GateGroup'), ('smart_cities', 'Smart Cities by Banorte'), ('open_innovation', 'Open Innovation by Banorte')], max_length=40),
        ),
        migrations.AlterField(
            model_name='friendscode',
            name='track_pref_1',
            field=models.CharField(blank=True, choices=[('fintech', 'Fintech by Capital One'), ('interactive_media', 'Smart Intelligence by GateGroup'), ('social_good', 'Smart Execution by GateGroup'), ('smart_cities', 'Smart Cities by Banorte'), ('open_innovation', 'Open Innovation by Banorte')], max_length=40),
        ),
        migrations.AlterField(
            model_name='friendscode',
            name='track_pref_2',
            field=models.CharField(blank=True, choices=[('fintech', 'Fintech by Capital One'), ('interactive_media', 'Smart Intelligence by GateGroup'), ('social_good', 'Smart Execution by GateGroup'), ('smart_cities', 'Smart Cities by Banorte'), ('open_innovation', 'Open Innovation by Banorte')], max_length=40),
        ),
        migrations.AlterField(
            model_name='friendscode',
            name='track_pref_3',
            field=models.CharField(blank=True, choices=[('fintech', 'Fintech by Capital One'), ('interactive_media', 'Smart Intelligence by GateGroup'), ('social_good', 'Smart Execution by GateGroup'), ('smart_cities', 'Smart Cities by Banorte'), ('open_innovation', 'Open Innovation by Banorte')], max_length=40),
        ),
    ]
