# Generated by Django 4.2.3 on 2025-08-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_applicationtypeconfig_access_token'),
        ('application', '0033_applicationtypeconfig_access_token'),
    ]

    operations = [
    ]
