# Generated by Django 4.2.3 on 2025-09-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_merge_20250817_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='track_selection_open',
            field=models.BooleanField(default=True, help_text='If disabled, teams cannot view or submit track preferences.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('P', 'Under review'), ('R', 'Wait listed'), ('RJ', 'Rejected'), ('I', 'Invited'), ('LR', 'Last reminder'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('A', 'Attended'), ('E', 'Expired'), ('D', 'Dubious'), ('IV', 'Invalid'), ('BL', 'Blocked'), ('NC', 'Needs change')], default='P', max_length=2),
        ),
    ]
