# Generated by Django 4.2.9 on 2025-10-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_broadcast_include_discord'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='judging_scores_public',
            field=models.BooleanField(
                default=False,
                help_text='If enabled, teams can view their released judging scores on the friends portal.'
            ),
        ),
    ]
