# Generated by Django 4.2.3 on 2025-02-15 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_edition_judging_scores_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='broadcasts/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='image_cid',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
