# Generated by Django 4.2.3 on 2025-08-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='under_age',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
