# Generated by GitHub Copilot
from django.db import migrations


def map_xxxl_to_xxl(apps, schema_editor):
    User = apps.get_model('user', 'User')
    # Update any existing XXXL values to XXL
    User.objects.filter(tshirt_size='XXXL').update(tshirt_size='XXL')


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0011_alter_user_level_of_study_length'),
    ]

    operations = [
        migrations.RunPython(map_xxxl_to_xxl, reverse_code=migrations.RunPython.noop),
    ]
