# Generated by Django 4.2.3 on 2025-08-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_map_xxxl_to_xxl_and_reduce_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name(s)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tshirt_size',
            field=models.CharField(choices=[('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL')], default='M', max_length=5),
        ),
    ]
