# Generated by Django 4.2.3 on 2025-10-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_judge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='judge_type',
            field=models.CharField(blank=True, choices=[('technical', 'Technical / Engineering'), ('product', 'Product / UX / Research'), ('business', 'Business / Strategy / Operations'), ('sponsor', 'Sponsor / Partner / Donor'), ('other', 'Other / Generalist')], help_text='Used to personalise judging assignments and reporting.', max_length=32),
        ),
    ]
